return {
  RenderMarkdownH1   = { fg = P.blue },
  RenderMarkdownH1Bg = { fg = P.blue, bg = P.dark_blue },
  RenderMarkdownH2   = { fg = P.purple },
  RenderMarkdownH2Bg = { fg = P.purple, bg = P.dark_purple },
  RenderMarkdownH3   = { fg = P.bright_green },
  RenderMarkdownH3Bg = { fg = P.bright_green, bg = P.dark_green },
  RenderMarkdownH4   = { fg = P.orange },
  RenderMarkdownH4Bg = { fg = P.orange, bg = P.dark_orange },
  RenderMarkdownH5   = { fg = P.yellow },
  RenderMarkdownH5Bg = { fg = P.yellow, bg = P.dark_yellow },
  RenderMarkdownH6   = { fg = P.cyan },
  RenderMarkdownH6Bg = { fg = P.cyan, bg = P.dark_cyan },
  RenderMarkdownCode = { fg = P.white, bg = P.bg_dark },
  RenderMarkdownLink = { fg = P.cyan },
}
